# Copyright (c) 2026 RoundPenny. All rights reserved.

apiVersion: v1
kind: ConfigMap
metadata:
  name: roundup-config
  namespace: roundup-platform
data:
  KAFKA_BROKERS: "kafka:9092"
  DATABASE_URL: "postgres://roundup:roundup@postgres:5432/roundup?sslmode=disable"
  JWT_SECRET: "change-this-in-production-to-a-random-64-char-string"
