# Copyright (c) 2026 RoundPenny. All rights reserved.

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "roundup-platform.fullname" . }}-backup
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "roundup-platform.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.backup.storageSize }}
