# Copyright (c) 2026 RoundPenny. All rights reserved.

{{- $svc := .Values.feeService -}}
{{- $name := "fee-service" -}}
{{ include "roundup-platform.service-template" (dict "service" $svc "name" $name) }}
