apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-exporter
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-exporter
  template:
    metadata:
      labels:
        app: redis-exporter
    spec:
      containers:
      - name: redis-exporter
        image: oliver006/redis_exporter:v1.64.0-alpine
        args:
          - "--redis.addr=redis://{{ .Values.global.redis.addr }}"
        ports:
          - containerPort: 9121
            name: metrics
        resources:
          requests:
            cpu: 50m
            memory: 32Mi
          limits:
            cpu: 100m
            memory: 64Mi
---
apiVersion: v1
kind: Service
metadata:
  name: redis-exporter
  namespace: {{ .Values.namespace }}
  labels:
    app: redis-exporter
spec:
  selector:
    app: redis-exporter
  ports:
    - port: 9121
      targetPort: 9121
      name: metrics
