# Copyright (c) 2026 RoundPenny. All rights reserved.

{{- $svc := .Values.roundupEngine -}}
{{- $name := "roundup-engine" -}}
{{ include "roundup-platform.service-template" (dict "service" $svc "name" $name) }}
