# Copyright (c) 2026 RoundPenny. All rights reserved.

{{- $svc := .Values.transactionService -}}
{{- $name := "transaction-service" -}}
{{ include "roundup-platform.service-template" (dict "service" $svc "name" $name) }}
